# Generated by Django 5.0.4 on 2024-05-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pet'),
        ('app', '0004_product'),
    ]

    operations = [
    ]
