# Generated by Django 5.0.4 on 2024-05-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_provider'),
        ('app', '0005_merge_0004_pet_0004_product'),
    ]

    operations = [
    ]
