# Generated by Django 5.0.4 on 2024-05-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_merge_0004_provider_0005_merge_0004_pet_0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="vet",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Dentista", "Dental"),
                    ("Traumatología", "Traumatology"),
                    ("Dermatología", "Dermatology"),
                    ("Cardiología", "Cardiology"),
                ],
                default="General",
                max_length=50,
            ),
        ),
    ]
