# Generated by Django 5.0.4 on 2024-05-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_merge_0004_provider_0005_merge_0004_pet_0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
