# Generated by Django 5.0.4 on 2024-05-21 04:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_pet_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                validators=[app.models.validate_weight],
            ),
        ),
    ]
