# Generated by Django 5.0.4 on 2024-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
