# Generated by Django 5.0.4 on 2024-05-23 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_vet_speciality"),
        ("app", "0009_alter_pet_weight"),
    ]

    operations = []
