# Generated by Django 5.0.4 on 2024-05-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_0007_vet_speciality_0009_alter_pet_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('Labrador Retriever', 'Labrador Retriever'), ('Pastor Alemán', 'Pastor Aleman'), ('Golden Retriever', 'Golden Retriever'), ('Beagle', 'Beagle'), ('Boxer', 'Boxer'), ('Siamés', 'Siames'), ('Europeo', 'Europeo'), ('Persa', 'Persa'), ('Bengalí', 'Bengali'), ('Sphynx', 'Sphynx')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vet',
            name='speciality',
            field=models.CharField(choices=[('General', 'General'), ('Dentista', 'Dentista'), ('Traumatología', 'Traumatologo'), ('Dermatología', 'Dermatologo'), ('Cardiología', 'Cardiologo')], default='General', max_length=50),
        ),
    ]
