# Generated by Django 5.0.4 on 2024-05-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_0007_vet_speciality_0009_alter_pet_weight'),
        ('app', '0010_provider_direccion'),
    ]

    operations = [
    ]
