# Generated by Django 5.0.4 on 2024-05-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_pet_breed_alter_vet_speciality'),
        ('app', '0011_merge_20240523_2344'),
    ]

    operations = [
    ]
