# Generated by Django 5.0.4 on 2024-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20240526_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
