# Generated by Django 5.0.4 on 2024-06-03 03:01

from django.db import migrations, models
from app.models import CityEnum

def copy_address_to_city(apps, schema_editor):
    Client = apps.get_model('app', 'Client')
    for client in Client.objects.all():
        client.city = client.address
        client.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20240526_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, choices=CityEnum.choices, blank=True),
        ),
        migrations.RunPython(copy_address_to_city),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
