# Generated by Django 5.0.4 on 2024-06-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_provider_direccion'),
        ('app', '0014_rename_address_to_city'),
    ]

    operations = [
    ]
