# Generated by Django 5.0.4 on 2024-06-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20240603_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('La Plata', 'La Plata'), ('Berisso', 'Berisso'), ('Ensenada', 'Ensenada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
